"""Seed script — inserts mock listing data into DynamoDB Items table.

Usage:
    python3 backend/scripts/seed_items.py

The table name is read from the CDK output or can be overridden:
    TABLE_NAME=SustainableAccessPlatformStack-Items python3 backend/scripts/seed_items.py
"""

import boto3
import os
from datetime import datetime, timezone
from decimal import Decimal

TABLE_NAME = os.environ.get(
    "TABLE_NAME", "SustainableAccessPlatformStack-Items"
)

SEED_USER_ID = "seed-user-001"  # placeholder owner for demo items
NOW = datetime.now(timezone.utc).isoformat()

S3_BASE = "https://sustainableaccessplatform-listingimagesbucket35876-phncghrg4bto.s3.us-east-1.amazonaws.com/items"

ITEMS = [
    # ── Existing items (updated with S3 image URLs) ──────────────────────
    {
        "item_id": "1",
        "owner_id": SEED_USER_ID,
        "title": "Makita Power Drill 18V",
        "category": "tools",
        "condition": "like_new",
        "description": "Professional-grade 18V cordless drill in excellent condition. Comes with 2 batteries, charger, and a full set of bits. Perfect for weekend DIY projects without the commitment of buying.",
        "pricing": {"borrow_price_per_day": 12, "resale_price": 85},
        "location": "Tempe, AZ",
        "latitude": 33.4340,
        "longitude": -111.9280,
        "status": "active",
        "image_url": f"{S3_BASE}/drill.png",
        "narration": "Hi, I'm a power drill! I only get used for about 13 minutes in my entire lifespan. Why not borrow me for your project and let someone else use me next?",
        "co2_saved_kg": 15.4,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "2",
        "owner_id": SEED_USER_ID,
        "title": "Vintage Fuji Film Camera",
        "category": "electronics",
        "condition": "good",
        "description": "Classic Fujifilm X-T10 with 35mm f/1.4 lens. Beautiful brown leather half-case included. This camera has character and produces stunning images with that vintage film look.",
        "pricing": {"borrow_price_per_day": 20, "resale_price": 250},
        "location": "Scottsdale, AZ",
        "latitude": 33.4150,
        "longitude": -111.9530,
        "status": "active",
        "image_url": f"{S3_BASE}/camera.png",
        "narration": "I've captured a thousand memories, but I have millions more to give. Take me with you on your next journey!",
        "co2_saved_kg": 32.1,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "3",
        "owner_id": SEED_USER_ID,
        "title": "Coleman Camping Tent 4-Person",
        "category": "outdoor",
        "condition": "fair",
        "description": "Reliable 4-person tent perfect for weekend camping trips. Easy setup, good waterproofing, and spacious interior. Minor wear on the rain fly but fully functional.",
        "pricing": {"borrow_price_per_day": 15, "resale_price": 60},
        "location": "Mesa, AZ",
        "latitude": 33.4450,
        "longitude": -111.9100,
        "status": "active",
        "image_url": f"{S3_BASE}/tent.png",
        "narration": "I'm meant to be under the stars, not stuck in a closet. Let's go camping — I promise I'll keep you dry!",
        "co2_saved_kg": 48.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "4",
        "owner_id": SEED_USER_ID,
        "title": "KitchenAid Stand Mixer",
        "category": "kitchen",
        "condition": "good",
        "description": "Classic KitchenAid stand mixer in excellent working condition. Perfect for baking projects, bread making, and more. Includes standard attachments.",
        "pricing": {"borrow_price_per_day": 18, "resale_price": 180},
        "location": "Phoenix, AZ",
        "latitude": 33.4380,
        "longitude": -111.9600,
        "status": "active",
        "image_url": f"{S3_BASE}/mixer.png",
        "narration": "Hi, I'm a KitchenAid mixer! I love helping bakers create delicious treats. Borrow me for your next baking adventure!",
        "co2_saved_kg": 25.2,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "5",
        "owner_id": SEED_USER_ID,
        "title": "Yoga Mat Premium",
        "category": "wellness",
        "condition": "like_new",
        "description": "High-quality cork yoga mat, barely used. Non-slip surface, eco-friendly materials. Perfect for yoga, pilates, or meditation.",
        "pricing": {"borrow_price_per_day": 5, "resale_price": 30},
        "location": "Tempe, AZ",
        "latitude": 33.4180,
        "longitude": -111.9350,
        "status": "active",
        "image_url": f"{S3_BASE}/yogamat.png",
        "narration": "I'm a premium yoga mat waiting to help you find your zen. Let's stretch together!",
        "co2_saved_kg": 8.7,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "6",
        "owner_id": SEED_USER_ID,
        "title": "Mountain Bike - Trek",
        "category": "sports",
        "condition": "good",
        "description": "Trek mountain bike, 21-speed, great for trails and city riding. Recently serviced with new brakes and tires. Helmet included.",
        "pricing": {"borrow_price_per_day": 25, "resale_price": 450},
        "location": "Scottsdale, AZ",
        "latitude": 33.4510,
        "longitude": -111.9450,
        "status": "active",
        "image_url": f"{S3_BASE}/bike.png",
        "narration": "I'm a Trek mountain bike ready for adventure! Let's hit the trails together.",
        "co2_saved_kg": 62.5,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "7",
        "owner_id": SEED_USER_ID,
        "title": "Standing Desk Converter",
        "category": "furniture",
        "condition": "like_new",
        "description": "Adjustable standing desk converter, fits most desks. Promotes better posture and productivity. Easy to set up, no tools required.",
        "pricing": {"borrow_price_per_day": 10, "resale_price": 120},
        "location": "Mesa, AZ",
        "latitude": 33.4100,
        "longitude": -111.9200,
        "status": "active",
        "image_url": f"{S3_BASE}/standingdesk.png",
        "narration": "Hi, I'm a standing desk converter! I'll help you work healthier. Try me before you buy!",
        "co2_saved_kg": 18.9,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "8",
        "owner_id": SEED_USER_ID,
        "title": "DJI Mini 3 Drone",
        "category": "electronics",
        "condition": "like_new",
        "description": "DJI Mini 3 drone with 4K camera. Lightweight, easy to fly, and produces stunning aerial footage. Includes 2 batteries and carrying case.",
        "pricing": {"borrow_price_per_day": 35, "resale_price": 400},
        "location": "Phoenix, AZ",
        "latitude": 33.4420,
        "longitude": -111.9700,
        "status": "active",
        "image_url": f"{S3_BASE}/drone.png",
        "narration": "I'm a DJI Mini 3 drone! I can capture breathtaking aerial views. Borrow me for your next shoot!",
        "co2_saved_kg": 44.2,
        "created_at": NOW,
        "updated_at": NOW,
    },
    # ── New items (linked to new images uploaded to S3) ──────────────────
    {
        "item_id": "9",
        "owner_id": SEED_USER_ID,
        "title": "Hiking Backpack 65L",
        "category": "outdoor",
        "condition": "good",
        "description": "65L hiking backpack with padded shoulder straps and hip belt. Perfect for weekend camping trips or day hikes. Multiple compartments and hydration sleeve.",
        "pricing": {"borrow_price_per_day": 10, "resale_price": 75},
        "location": "Tempe, AZ",
        "latitude": 33.4250,
        "longitude": -111.9400,
        "status": "active",
        "image_url": f"{S3_BASE}/backpack.png",
        "narration": "Hi, I'm your next adventure companion! I can carry everything you need for a weekend in the wilderness. Let's explore!",
        "co2_saved_kg": 20.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "10",
        "owner_id": SEED_USER_ID,
        "title": "5-Shelf Bookcase",
        "category": "furniture",
        "condition": "good",
        "description": "Solid wood 5-shelf bookcase, 72 inches tall. Fits perfectly in living rooms or home offices. Easy to assemble and very sturdy.",
        "pricing": {"borrow_price_per_day": 8, "resale_price": 90},
        "location": "Phoenix, AZ",
        "latitude": 33.4500,
        "longitude": -111.9650,
        "status": "active",
        "image_url": f"{S3_BASE}/bookshelf.png",
        "narration": "I'm a bookshelf full of potential — ready to display your favorite reads. Borrow me to see if I fit your space!",
        "co2_saved_kg": 30.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "11",
        "owner_id": SEED_USER_ID,
        "title": "Cast Iron Skillet Set",
        "category": "kitchen",
        "condition": "good",
        "description": "Lodge cast iron skillet set (8-inch and 12-inch). Pre-seasoned and ready to cook. Perfect for stovetop and oven use. Build incredible flavor over time.",
        "pricing": {"borrow_price_per_day": 6, "resale_price": 55},
        "location": "Scottsdale, AZ",
        "latitude": 33.4200,
        "longitude": -111.9250,
        "status": "active",
        "image_url": f"{S3_BASE}/castiron.png",
        "narration": "I'm a cast iron skillet that gets better with age! Try me for a weekend of cooking before committing.",
        "co2_saved_kg": 12.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "12",
        "owner_id": SEED_USER_ID,
        "title": "Coffee Table Books Bundle",
        "category": "books",
        "condition": "like_new",
        "description": "A curated collection of 5 stunning coffee table books on architecture, photography, and design. Perfect for decorating and inspiring. Barely touched.",
        "pricing": {"borrow_price_per_day": 4, "resale_price": 45},
        "location": "Tempe, AZ",
        "latitude": 33.4300,
        "longitude": -111.9320,
        "status": "active",
        "image_url": f"{S3_BASE}/coffeebooks.png",
        "narration": "We're a collection of five stunning books waiting to spark your creativity and transform any coffee table into a conversation piece.",
        "co2_saved_kg": 5.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "13",
        "owner_id": SEED_USER_ID,
        "title": "De'Longhi Espresso Machine",
        "category": "kitchen",
        "condition": "like_new",
        "description": "De'Longhi Dedica espresso machine. Makes barista-quality espresso at home. Compact design, built-in milk frother. Try before you invest in one!",
        "pricing": {"borrow_price_per_day": 15, "resale_price": 200},
        "location": "Mesa, AZ",
        "latitude": 33.4370,
        "longitude": -111.9180,
        "status": "active",
        "image_url": f"{S3_BASE}/espresso.png",
        "narration": "I'm an espresso machine that makes café quality coffee at home. Borrow me for a week and decide if I deserve a permanent spot in your kitchen!",
        "co2_saved_kg": 22.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "14",
        "owner_id": SEED_USER_ID,
        "title": "Portable BBQ Grill",
        "category": "outdoor",
        "condition": "good",
        "description": "Weber portable charcoal grill, perfect for tailgating, camping, and backyard cookouts. Compact and easy to clean. Comes with all accessories.",
        "pricing": {"borrow_price_per_day": 12, "resale_price": 80},
        "location": "Phoenix, AZ",
        "latitude": 33.4460,
        "longitude": -111.9580,
        "status": "active",
        "image_url": f"{S3_BASE}/grill.png",
        "narration": "I'm your weekend BBQ hero! No need to buy a grill that sits in the garage — borrow me for your next cookout!",
        "co2_saved_kg": 18.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "15",
        "owner_id": SEED_USER_ID,
        "title": "Sony WH-1000XM5 Headphones",
        "category": "electronics",
        "condition": "like_new",
        "description": "Sony's flagship noise-cancelling headphones. Crystal clear audio with industry-leading ANC. Perfect for travel, focus work, or just enjoying music. Includes case.",
        "pricing": {"borrow_price_per_day": 15, "resale_price": 280},
        "location": "Tempe, AZ",
        "latitude": 33.4160,
        "longitude": -111.9420,
        "status": "active",
        "image_url": f"{S3_BASE}/headphones.png",
        "narration": "Hi, I'm Sony's best noise-cancelling headphones. Try me on a long flight or work session — you might never want to give me back!",
        "co2_saved_kg": 28.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "16",
        "owner_id": SEED_USER_ID,
        "title": "North Face Fleece Jacket",
        "category": "clothing",
        "condition": "good",
        "description": "North Face full-zip fleece jacket, size M. Super warm and lightweight. Perfect for hiking, camping, or casual wear. Barely worn.",
        "pricing": {"borrow_price_per_day": 5, "resale_price": 60},
        "location": "Scottsdale, AZ",
        "latitude": 33.4490,
        "longitude": -111.9390,
        "status": "active",
        "image_url": f"{S3_BASE}/jacket.png",
        "narration": "I'm a cozy North Face fleece that keeps you warm on cold nights. Why buy when you can borrow me for your next outdoor adventure?",
        "co2_saved_kg": 8.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "17",
        "owner_id": SEED_USER_ID,
        "title": "Sit-on-Top Kayak",
        "category": "outdoor",
        "condition": "good",
        "description": "10-foot sit-on-top kayak with paddle included. Great for calm lakes and slow rivers. Stable and easy for beginners. Perfect for a day on the water.",
        "pricing": {"borrow_price_per_day": 30, "resale_price": 350},
        "location": "Mesa, AZ",
        "latitude": 33.4530,
        "longitude": -111.9080,
        "status": "active",
        "image_url": f"{S3_BASE}/kayak.png",
        "narration": "I'm a kayak just waiting for my next paddling adventure. Borrow me for a day on the water — no storage headaches for you!",
        "co2_saved_kg": 55.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "18",
        "owner_id": SEED_USER_ID,
        "title": "College Textbook Bundle",
        "category": "books",
        "condition": "good",
        "description": "Bundle of 6 college textbooks: Calculus, Organic Chemistry, Computer Science, Psychology, Economics, and Biology. Save hundreds vs. buying new.",
        "pricing": {"borrow_price_per_day": 8, "resale_price": 120},
        "location": "Tempe, AZ",
        "latitude": 33.4215,
        "longitude": -111.9345,
        "status": "active",
        "image_url": f"{S3_BASE}/textbooks.png",
        "narration": "We're six textbooks that cost a fortune new. Borrow us for a semester and save your money for something that actually matters!",
        "co2_saved_kg": 10.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "19",
        "owner_id": SEED_USER_ID,
        "title": "Herman Miller Aeron Chair",
        "category": "furniture",
        "condition": "good",
        "description": "Herman Miller Aeron ergonomic chair, size B. The gold standard in office chairs. Perfect for trying before investing $1,500+. Lumbar support, adjustable arms.",
        "pricing": {"borrow_price_per_day": 20, "resale_price": 800},
        "location": "Phoenix, AZ",
        "latitude": 33.4410,
        "longitude": -111.9620,
        "status": "active",
        "image_url": f"{S3_BASE}/aeron-chair.jpeg",
        "narration": "I'm the chair that transformed millions of backs. Borrow me for a week and see if I deserve a permanent spot in your office.",
        "co2_saved_kg": 45.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "20",
        "owner_id": SEED_USER_ID,
        "title": "DeWalt Circular Saw 7.25\"",
        "category": "tools",
        "condition": "like_new",
        "description": "DeWalt 7.25-inch circular saw with carbide blade. Perfect for woodworking projects. 15-amp motor, 5500 RPM. Borrow it for your renovation project.",
        "pricing": {"borrow_price_per_day": 20, "resale_price": 130},
        "location": "Tempe, AZ",
        "latitude": 33.4280,
        "longitude": -111.9470,
        "status": "active",
        "image_url": f"{S3_BASE}/dewalt-circular-saw.jpeg",
        "narration": "I'm a professional DeWalt circular saw. Why buy a $150 tool for one project? Borrow me instead!",
        "co2_saved_kg": 20.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "21",
        "owner_id": SEED_USER_ID,
        "title": "iPad Pro + Apple Pencil",
        "category": "electronics",
        "condition": "like_new",
        "description": "12.9-inch iPad Pro (2022) with Apple Pencil 2nd gen. Perfect for digital art, note-taking, or trying creative work before committing to the purchase.",
        "pricing": {"borrow_price_per_day": 25, "resale_price": 900},
        "location": "Scottsdale, AZ",
        "latitude": 33.4130,
        "longitude": -111.9510,
        "status": "active",
        "image_url": f"{S3_BASE}/ipadpro-applepencil.jpeg",
        "narration": "I'm an iPad Pro with Apple Pencil — a digital canvas for artists. Try me before buying, creativity awaits!",
        "co2_saved_kg": 35.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "22",
        "owner_id": SEED_USER_ID,
        "title": "Meditation Cushion + Singing Bowl Set",
        "category": "wellness",
        "condition": "like_new",
        "description": "Premium zafu meditation cushion with buckwheat filling, plus a handcrafted Tibetan singing bowl set. Perfect for deepening your practice.",
        "pricing": {"borrow_price_per_day": 8, "resale_price": 65},
        "location": "Mesa, AZ",
        "latitude": 33.4190,
        "longitude": -111.9150,
        "status": "active",
        "image_url": f"{S3_BASE}/meditation-cusion-singing-bowlset.jpeg",
        "narration": "We're a meditation cushion and singing bowl set ready to elevate your mindfulness practice. Borrow us and find your inner peace.",
        "co2_saved_kg": 7.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "23",
        "owner_id": SEED_USER_ID,
        "title": "North Face Winter Parka",
        "category": "clothing",
        "condition": "like_new",
        "description": "North Face 550-fill down winter parka, size L. Waterproof exterior, incredibly warm. Perfect for ski trips or cold climates. Barely worn — Arizona weather!",
        "pricing": {"borrow_price_per_day": 12, "resale_price": 180},
        "location": "Phoenix, AZ",
        "latitude": 33.4540,
        "longitude": -111.9750,
        "status": "active",
        "image_url": f"{S3_BASE}/northface-winter-parka.jpeg",
        "narration": "I'm a warm North Face parka that rarely gets used in Arizona. Borrow me for your ski trip — no need to buy a coat you'll only need twice a year!",
        "co2_saved_kg": 12.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "24",
        "owner_id": SEED_USER_ID,
        "title": "Bluetooth Portable Projector",
        "category": "electronics",
        "condition": "good",
        "description": "Anker portable Bluetooth projector. 1080p, 700 ANSI lumens. Perfect for movie nights, presentations, or outdoor screenings. Compact and battery-powered.",
        "pricing": {"borrow_price_per_day": 20, "resale_price": 250},
        "location": "Tempe, AZ",
        "latitude": 33.4350,
        "longitude": -111.9380,
        "status": "active",
        "image_url": f"{S3_BASE}/portable-bluetooth-projector.jpeg",
        "narration": "I'm a portable projector that turns any wall into a cinema screen. Borrow me for movie night — no big screen required!",
        "co2_saved_kg": 25.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "25",
        "owner_id": SEED_USER_ID,
        "title": "Pressure Washer 3000 PSI",
        "category": "tools",
        "condition": "good",
        "description": "3000 PSI gas-powered pressure washer. Cleans driveways, patios, decks, and vehicles with ease. Perfect for spring cleaning without owning a machine you use twice a year.",
        "pricing": {"borrow_price_per_day": 35, "resale_price": 280},
        "location": "Scottsdale, AZ",
        "latitude": 33.4480,
        "longitude": -111.9360,
        "status": "active",
        "image_url": f"{S3_BASE}/pressure-washer-3000psi.jpeg",
        "narration": "I'm a 3000 PSI pressure washer ready to blast away grime! Borrow me instead of buying — you only need me a couple times a year anyway.",
        "co2_saved_kg": 30.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "26",
        "owner_id": SEED_USER_ID,
        "title": "Theragun Pro Massage Gun",
        "category": "wellness",
        "condition": "like_new",
        "description": "Theragun Pro percussive therapy device. 16mm amplitude, professional-grade for muscle recovery. 5 attachments included. Perfect for athletes and weekend warriors.",
        "pricing": {"borrow_price_per_day": 15, "resale_price": 250},
        "location": "Mesa, AZ",
        "latitude": 33.4220,
        "longitude": -111.9230,
        "status": "active",
        "image_url": f"{S3_BASE}/theragun-pro-massage-gun.jpeg",
        "narration": "I'm a Theragun Pro — the massage therapist you can take anywhere. Borrow me for a week of recovery and feel the difference!",
        "co2_saved_kg": 15.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
    {
        "item_id": "27",
        "owner_id": SEED_USER_ID,
        "title": "Wilson Tennis Racket Set",
        "category": "sports",
        "condition": "good",
        "description": "Set of 2 Wilson tennis rackets with 3 balls and carrying bag. Perfect for casual play or trying the sport before investing in your own gear.",
        "pricing": {"borrow_price_per_day": 8, "resale_price": 70},
        "location": "Phoenix, AZ",
        "latitude": 33.4380,
        "longitude": -111.9560,
        "status": "active",
        "image_url": f"{S3_BASE}/wilson-racket-set.jpeg",
        "narration": "We're a pair of Wilson tennis rackets ready for a match! Borrow us and see if you've got a new favourite sport.",
        "co2_saved_kg": 10.0,
        "created_at": NOW,
        "updated_at": NOW,
    },
]


def _to_decimal(value):
    """Recursively convert floats to Decimal for DynamoDB compatibility."""
    if isinstance(value, float):
        return Decimal(str(value))
    if isinstance(value, dict):
        return {k: _to_decimal(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_to_decimal(v) for v in value]
    return value


def seed():
    dynamodb = boto3.resource("dynamodb", region_name="us-east-1")
    table = dynamodb.Table(TABLE_NAME)

    print(f"Seeding {len(ITEMS)} items into {TABLE_NAME}...")

    for item in ITEMS:
        # Remove None values — DynamoDB doesn't accept None
        # Convert floats to Decimal — DynamoDB requirement
        clean_item = {k: _to_decimal(v) for k, v in item.items() if v is not None}
        table.put_item(Item=clean_item)
        print(f"  ✓ {item['title']}")

    print(f"\nDone! {len(ITEMS)} items seeded.")
    print(f"\nVerify with:")
    print(f"  aws dynamodb scan --table-name {TABLE_NAME} --select COUNT")


if __name__ == "__main__":
    seed()
